### ISSUE TITLE
Cache files are world-readable

### ISSUE THREAD

**Issue by RulerOf** [DannyBen/lightly#20]
Hi,

Was looking at lightly to make fetching temporary AWS credentials a little less cumbersome, but discovered that the cache files are world-readable due to the default umask of `022`. On Mac OS:

```
╰─❯ ll ~/.tkhelper
total 8
drwxr-xr-x    3 andrewbobulsky  staff    96B May 15 23:34 .
drwxr-x---+ 132 andrewbobulsky  staff   4.1K May 15 23:34 ..
-rw-r--r--    1 andrewbobulsky  staff   1.2K May 15 23:34 8f16a569e487a1990ef3ebaf7512a567
```

I think the right technique would be to save the starting umask, write the file then restore it, in [this function](https://github.com/DannyBen/lightly/blob/15fff0734a5660a9235b8f76865274bc5b66b8dc/lib/lightly/cache_operations.rb#L78):

```ruby
    def save(key, content)
      FileUtils.mkdir_p dir
      path = get_path key
      umask_backup = File.umask 0o077 # This returns the current umask when setting a new one
      File.binwrite path, Marshal.dump(content)
      File.umask umask_backup
    end
```

Thought this would be a useful suggestion. Thanks!

**Comment by DannyBen** [comment]
How about having the `save` method just run `chmod` on the file, but only if the lightly setting `permissions` has been set?

Something like this:

```ruby
def save(key, content)
  FileUtils.mkdir_p dir
  path = get_path key
  File.binwrite path, Marshal.dump(content)
  return unless permissions

  FileUtils.chmod permissions, path
end
```

Then you can simply set 

```ruby
Lightly.permissions = 0640
Lightly.get ...
```

**Comment by DannyBen** [comment]
The PR adds this functionality. Specifically [this `Lightly#cache_operations` change](https://github.com/DannyBen/lightly/pull/21/files#diff-d072b8703f6d20a93754312542d8563daaef8acda936a815e1d17903b0c45fcb).

**Comment by DannyBen** [comment]
I have implemented this `permissions` options both in Lightly and in the sister gem, WebCache.
I will be waiting for your input before merging, hoping this fits your needs.

**Comment by RulerOf** [comment]
Wow! So first things first, this absolutely gets the job done.

> How about having the save method just run chmod on the file, but only if the lightly setting permissions has been set?

The reason I didn't suggest the `chmod` route is because this does cause the file with the potentially-sensitve data to be written to disk as world-readable for some amount of time. AFAIK the only way to prevent that with the syscall underlying `File.binwrite` is to modify the umask.

Having the option to set permissions on the cache is reasonable. I didn't suggest it initially because I thought it was more work 😂

Sticking with the `permissions` UX as implemented here, I would still recommend the umask approach to resolve the security concern, although my rendition is a little ugly:

```ruby
def save(key, content)
  FileUtils.mkdir_p dir
  path = get_path key

  umask_backup = File.umask 0o077 if permissions
  File.binwrite path, Marshal.dump(content)
  File.umask umask_backup if permissions
  return unless permissions

  FileUtils.chmod permissions, path
end
```

To be clear, my needs are not this sophisticated. I'd be happy with the merge as-is. Thanks so much for your time and for this lovely little gem 😊

**Comment by DannyBen** [comment]
I prefer avoiding messing with umask. It doesn't sit right.

This seems to be working as well

```ruby
    def save(key, content)
      FileUtils.mkdir_p dir
      path = get_path key
      File.open path, 'wb', permissions do |file|
        file.write Marshal.dump(content)
      end
    end
```

can you confirm that this part behaves properly for you?

```ruby
File.open path, 'wb', 0o600 do |file|
  file.write Marshal.dump(content)
end
```

**Comment by RulerOf** [comment]
Confirmed on Mac OS:

```
╭─ ~/scratch/lightlytest                                                                                                  12:50:31
╰─❯ ll
total 0
drwxr-xr-x   2 andrewbobulsky  staff    64B May 18 12:50 .
drwxr-xr-x  32 andrewbobulsky  staff   1.0K May 18 12:50 ..
╭─ ~/scratch/lightlytest                                                                                                  12:50:32
╰─❯ irb
irb(main):001:0> path = "./test"
=> "./test"
irb(main):002:0> content = "testdata"
=> "testdata"
irb(main):003:1* File.open path, 'wb', 0o600 do |file|
irb(main):004:1*   file.write Marshal.dump(content)
irb(main):005:0> end
=> 18
irb(main):006:0> exit
╭─ ~/scratch/lightlytest                                                                                              37s 12:51:10
╰─❯ ll
total 8
drwxr-xr-x   3 andrewbobulsky  staff    96B May 18 12:51 .
drwxr-xr-x  32 andrewbobulsky  staff   1.0K May 18 12:50 ..
-rw-------   1 andrewbobulsky  staff    18B May 18 12:51 test
╭─ ~/scratch/lightlytest                                                                                                  12:51:12
╰─❯ cat test
testdata:ET%
╭─ ~/scratch/lightlytest                                                                                                  12:52:16
╰─❯
```

**Comment by DannyBen** [comment]
Cool. So I will merge both here and in webcache, and release tomorrow.
Thanks for raising this issue.

**Comment by DannyBen** [comment]
Version [0.4.0](https://github.com/DannyBen/lightly/releases/tag/v0.4.0) is released with this change.
